image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

# build docker container and push it into the private registry of this repo
build:
  stage: build
  script:
    # logging into Gitlab's private container registry using credentials created 
    # for this purpose, building our container and pushing into the registry 
    - docker login -u "$CI_REGISTRY_USER" -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/learnshell-2.0/ls-web .
    - docker push $CI_REGISTRY/learnshell-2.0/ls-web
  ## only build in case of commit made in the master branch
  #only:
  #  - master 
    
# toggle rebuild of pod containing the container built in the previous stage    
deploy:
  stage: deploy
  image: alpine:latest
  script:
    # installing kubectl using curl (as recommended in Google's docs)
    - apk update  && apk add --no-cache curl
    - 'curl --data {\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"kubectl.kubernetes.io/restartedAt\":\"2006-01-02T15:04:05Z07:00\"}}}}} -X PATCH -H "Accept: application/json, */*" -H "Content-Type: application/strategic-merge-patch+json" -H "Authorization: Bearer $KUBE_SERVICEACCOUNT_TOKEN" https://35.187.2.233/apis/apps/v1/namespaces/learnshell/deployments/web/ --insecure'
  ## only deploy in case of commit made in the master branch
  #only:
  #  - master
