type ScoreHistogram {
    label: [Float]
    frequency: [Int]
}
type Assignments {
    assignmentName: String
    assignmentMedianPercentage: Float
    assignmentMedian: Float
    assignmentMaxScore: Float
}
type Parallels {
    name: String
    teacher: String
    numOfStudents: Int
    median: Float
    percentileAverage: Float
}
type Students {
    name: String
    username: String
    parallel: String
    score: String
    percentile: String
}
type TeachersDashboardData {
    median: Float
    maxScore: Float
    minScore: Float
    studentsNumber: Int
    overallMedianHistory: [String]
    medianHistory: [String]
    lastYearOverallMedian: [String]
    scoreHistogram: ScoreHistogram
    assignments: [Assignments]
    numberOfWeeks: Int
    parallels: [Parallels]
    students: [Students]
}
